#
#$$$$$$$$\                   $$\     $$$$$$$\ $$$$$$$$\ $$$$$$$\
#$$  _____|                  $$ |    $$  __$$\\__$$  __|$$  __$$\
#$$ |   $$$$$$\   $$$$$$$\ $$$$$$\   $$ |  $$ |  $$ |   $$ |  $$ |
#$$$$$\ \____$$\ $$  _____|\_$$  _|  $$$$$$$  |  $$ |   $$$$$$$  |
#$$  __|$$$$$$$ |\$$$$$$\    $$ |    $$  __$$<   $$ |   $$  ____/
#$$ |  $$  __$$ | \____$$\   $$ |$$\ $$ |  $$ |  $$ |   $$ |
#$$ |  \$$$$$$$ |$$$$$$$  |  \$$$$  |$$ |  $$ |  $$ |   $$ |
#\__|   \_______|\_______/    \____/ \__|  \__|  \__|   \__|
############################################################
#This plugin is made by SkyfightTV for everyone
#It works between spigot version 1.7 and 1.18
#This plugin can't be reloaded


#Permission to use the rtp
#If u give this permission to everyone, all players can use the rtp.
permission: "fastrtp"

#The radius of the RTP
minRadius: 100
maxRadius: 1500

#All materials that prevent rtp.
blackListMaterial:
  - "LAVA"
  - "WATER"
